### ISSUE TITLE
Cannot Read Property 'Find' of undefined

### ISSUE THREAD

**Issue by l-c** [marcospcury/gatsby-plugin-translate#1]
I'm getting this error when running gatsby develop.

I have created a folder named translations and added an en and es json with a single translation. I debugged the useTranslation function and the translation map is undefined. 

`
{
      resolve: `gatsby-plugin-translate`,
      options: {
        sourceLanguage: 'en',
        targetLanguages: ['en', 'es'],
      }
    }
`

` ERROR #11321  PLUGIN

"gatsby-plugin-translate" threw an error while running the onCreateNode lifecycle:

Cannot read property 'find' of undefined

  85 |             }
  86 |
> 87 |             translation = pipe(getSelectorFromInternalType, getTranslation(options))(node);
     |                                                                                     ^
  88 |
  89 |             if (!translation) {
  90 |               _context2.next = 8;

File: node_modules/gatsby-plugin-translate/gatsby-node.js:87:85`

**Comment by jodiedoubleday** [comment]
I also have the same issue.

**Comment by marcospcury** [comment]
Hi there. Thank you for the feedback. Can you please try again with version 1.1.3?
