### ISSUE TITLE
[Help] Cant get it to work

### ISSUE THREAD

**Issue by lauridskern** [marcospcury/gatsby-plugin-translate#2]
Hi, I just can't get the translation to work on my page. It translates the slugs correctly so the API seems to work but none of the text of my pages is getting translated.
The static translations Part is not required only optional, right?
Also, some of my pages are generated from .mdx files, could this be a problem?

**Comment by marcospcury** [comment]
Hi
Yes, the static translations are optional. Are you having trouble translating the graphQL content? If so, what's the node's origin? (eg another plugin) 

I'd appreciate if you'd share your plugin's config too.

Thanks!

**Comment by lauridskern** [comment]
Hi
Thanks for the quick response!
I'm not using any graphQL content only static text. Some pages are generated from mdx files and some text are hardcoded. 

> {
>       resolve: `gatsby-plugin-translate`,
>       options: {
>         googleApiKey: '*******'
>         sourceLanguage: 'de',
>         targetLanguages: ['en'],
>         translateSlug: true
>       },
> }

**Comment by marcospcury** [comment]
Ok, I got what happened. The Google API was planned to work on either GraphQL nodes or slugs. Static / hardcoded text should be translated manually through the json files. But that's just another use case I haven't thought yet. Though the implementation is not that simple, as I would have to extract all of your text during build time (GraphQL and slugs have specific events on build that I use to translate automatically). That's an interesting scenario, but I have to put some thought on how to make it work.

**Comment by lauridskern** [comment]
Ohh I see. That would be amazing if that works. Could really change the game in terms of translations. You could make a micro saas out of it. Maybe extract all the strings to a server, there you can translate them manually or automatically and they get fetched on build time to a static page. If that makes sense haha
